alias: BSC discovery
description: ""
triggers:
  - topic: bsc/DataDevice/+/valid
    enabled: true
    payload: "1"
    trigger: mqtt
    alias: DataDevice
  - topic: bsc/DataDevice/+/cellVoltage/#
    enabled: true
    trigger: mqtt
    alias: Cell Voltages
  - topic: bsc/DataDevice/+/temperature/#
    enabled: true
    trigger: mqtt
    alias: DataDevice Temperatures
  - alias: 1wire Temperature
    topic: bsc/temperatur/#
    enabled: true
    trigger: mqtt
conditions: []
actions:
  - choose:
      - conditions:
          - condition: and
            conditions:
              - condition: template
                value_template: "{{ trigger.topic.split('/')[3] == \"temperature\" }}"
        sequence:
          - action: mqtt.publish
            data:
              qos: 0
              topic: >-
                homeassistant/sensor/bsc0_{{ trigger.topic.split('/')[2]}}{{
                trigger.topic.split('/')[3]}}/{{trigger.topic.split('/')[4]}}{{trigger.topic.split('/')[5]}}/config
              payload: |-
                {
                  "name": "Temperature Sensor {{ trigger.topic.split('/')[4]|int +1}}",
                  "state_topic": "{{ trigger.topic }}",
                  "device_class": "temperature",
                  "state_class": "measurement",
                  "value_template": "{% raw %} {{ value }} {% endraw %}",
                  "unit_of_measurement": "°C",
                  "unique_id": "bsc_{{ trigger.topic.split('/')[2]}}_{{ trigger.topic.split('/')[3]}}_{{trigger.topic.split('/')[4]|int +1}}",
                  "device": {
                    "identifiers": ["bsc_{{ trigger.topic.split('/')[1]}}_{{ trigger.topic.split('/')[2]}}"],
                    "name": "BSC {{ trigger.topic.split('/')[1]}} {{ trigger.topic.split('/')[2]}}",
                    "manufacturer": "BSC",
                    "model": "BSC",
                    "sw_version": "n/a",
                    "hw_version": "n/a",
                    "configuration_url": "http://bsc.my.home"
                  }
                }
            alias: Temperatures
        alias: Temperatures
      - conditions:
          - condition: and
            conditions:
              - condition: template
                value_template: "{{ trigger.payload != '0' }}"
              - condition: template
                value_template: "{{ trigger.topic.split('/')[3] == \"cellVoltage\" }}"
        sequence:
          - action: mqtt.publish
            data:
              qos: 0
              topic: >-
                homeassistant/sensor/bsc0_{{ trigger.topic.split('/')[2]}}{{
                trigger.topic.split('/')[3]}}/{{trigger.topic.split('/')[4]}}{{trigger.topic.split('/')[5]}}/config
              payload: |-
                {
                  "name": "Cell {% if trigger.topic.split('/')[4]|int < 9 %}0{% else %}{% endif %}{{ trigger.topic.split('/')[4]|int +1}} Voltage",
                  "state_topic": "{{ trigger.topic }}",
                  "device_class": "voltage",
                  "state_class": "measurement",
                  "value_template": "{% raw %} {{ value|int / 1000 }} {% endraw %}",
                  "unit_of_measurement": "V",
                  "unique_id": "bsc__{{ trigger.topic.split('/')[2]}}_{{trigger.topic.split('/')[3]}}{% if trigger.topic.split('/')[4]|int < 9 %}0{% else %}{% endif %}{{ trigger.topic.split('/')[4]|int +1}}",
                  "device": {
                    "identifiers": ["bsc_{{ trigger.topic.split('/')[1]}}_{{ trigger.topic.split('/')[2]}}"],
                    "name": "BSC {{ trigger.topic.split('/')[1]}} {{ trigger.topic.split('/')[2]}}"
                  }
                }
            alias: cellVoltages
        alias: CellVoltages
      - conditions:
          - condition: template
            value_template: "{{ trigger.topic.split('/')[3] != \"cellVoltage\" }}"
        sequence:
          - action: mqtt.publish
            data:
              qos: 0
              topic: >-
                homeassistant/sensor/bsc0_{{ trigger.topic.split('/')[2]}}{{
                trigger.topic.split('/')[3]}}/SoC/config
              payload: |-
                {
                  {%- set attrib = "SoC" -%}
                  "name": "SoC",
                  "state_topic": "{{ trigger.topic.replace("valid", attrib)}}",
                  "device_class": "battery",
                  "state_class": "measurement",
                  "unit_of_measurement": "%",
                  "unique_id": "bsc_{{ trigger.topic.split('/')[2]}}_{{ trigger.topic.split('/')[3]}}_{{ attrib}}",
                  "device": {
                    "identifiers": ["bsc_{{ trigger.topic.split('/')[1]}}_{{ trigger.topic.split('/')[2]}}"]
                  }
                }
            alias: SoC
          - action: mqtt.publish
            data:
              qos: 0
              topic: >-
                homeassistant/sensor/bsc0_{{ trigger.topic.split('/')[2]}}{{
                trigger.topic.split('/')[3]}}/totalVoltage/config
              payload: |-
                {
                  {%- set attrib = "totalVoltage" -%}
                  "name": "Total Voltage",
                  "state_topic": "{{ trigger.topic.replace("valid", attrib)}}",
                  "device_class": "voltage",
                  "state_class": "measurement",
                  "unit_of_measurement": "V",
                  "unique_id": "bsc0_{{ trigger.topic.split('/')[2]}}_{{ trigger.topic.split('/')[3]}}_{{ attrib}}",
                  "device": {
                    "identifiers": ["bsc_{{ trigger.topic.split('/')[1]}}_{{ trigger.topic.split('/')[2]}}"]
                  }
                }
            alias: totalVoltage
          - action: mqtt.publish
            data:
              qos: 0
              topic: >-
                homeassistant/sensor/bsc0_{{ trigger.topic.split('/')[2]}}{{
                trigger.topic.split('/')[3]}}/cellVoltageMax/config
              payload: |-
                {
                  {%- set attrib = "cellVoltageMax" -%}
                  "name": "Max Cell Voltage",
                  "state_topic": "{{ trigger.topic.replace("valid", attrib)}}",
                  "device_class": "voltage",
                  "state_class": "measurement",
                  "unit_of_measurement": "V",
                  "value_template": "{% raw %} {{ value|int / 1000 }} {% endraw %}",
                  "unique_id": "bsc0_{{ trigger.topic.split('/')[2]}}_{{ trigger.topic.split('/')[3]}}_{{ attrib}}",
                  "device": {
                    "identifiers": ["bsc_{{ trigger.topic.split('/')[1]}}_{{ trigger.topic.split('/')[2]}}"]
                  }
                }
            alias: cellVoltageMax
          - action: mqtt.publish
            data:
              qos: 0
              topic: >-
                homeassistant/sensor/bsc0_{{ trigger.topic.split('/')[2]}}{{
                trigger.topic.split('/')[3]}}/cellVoltageMin/config
              payload: |-
                {
                  {%- set attrib = "cellVoltageMin" -%}
                  "name": "Min Cell Voltage",
                  "state_topic": "{{ trigger.topic.replace("valid", attrib)}}",
                  "device_class": "voltage",
                  "state_class": "measurement",
                  "unit_of_measurement": "V",
                  "value_template": "{% raw %} {{ value|int / 1000 }} {% endraw %}",
                  "unique_id": "bsc0_{{ trigger.topic.split('/')[2]}}_{{ trigger.topic.split('/')[3]}}_{{ attrib}}",
                  "device": {
                    "identifiers": ["bsc_{{ trigger.topic.split('/')[1]}}_{{ trigger.topic.split('/')[2]}}"]
                  }
                }
            alias: cellVoltageMin
          - action: mqtt.publish
            data:
              qos: 0
              topic: >-
                homeassistant/sensor/bsc0_{{ trigger.topic.split('/')[2]}}{{
                trigger.topic.split('/')[3]}}/maxCellDifferenceVoltage/config
              payload: |-
                {
                  {%- set attrib = "maxCellDifferenceVoltage" -%}
                  "name": "Delta Voltage",
                  "state_topic": "{{ trigger.topic.replace("valid", attrib)}}",
                  "device_class": "voltage",
                  "state_class": "measurement",
                  "value_template": "{% raw %} {{ value|int / 1000 }} {% endraw %}",
                  "unit_of_measurement": "V",
                  "unique_id": "bsc0_{{ trigger.topic.split('/')[2]}}_{{ trigger.topic.split('/')[3]}}_{{ attrib}}",
                  "device": {
                    "identifiers": ["bsc_{{ trigger.topic.split('/')[1]}}_{{ trigger.topic.split('/')[2]}}"]
                  }
                }
            alias: maxCellDifferenceVoltage
          - action: mqtt.publish
            data:
              qos: 0
              topic: >-
                homeassistant/sensor/bsc0_{{ trigger.topic.split('/')[2]}}{{
                trigger.topic.split('/')[3]}}/totalCurrent/config
              payload: |-
                {
                  {%- set attrib = "totalCurrent" -%}
                  "name": "Total Current",
                  "state_topic": "{{ trigger.topic.replace("valid", attrib)}}",
                  "device_class": "current",
                  "state_class": "measurement",
                  "unit_of_measurement": "A",
                  "unique_id": "bsc0_{{ trigger.topic.split('/')[2]}}_{{ trigger.topic.split('/')[3]}}_{{ attrib}}",
                  "device": {
                    "identifiers": ["bsc_{{ trigger.topic.split('/')[1]}}_{{ trigger.topic.split('/')[2]}}"]
                  }
                }
            alias: totalCurrent
        alias: Rest
mode: parallel
max: 10
